### ISSUE TITLE
nuxt ssr框架引入vue-wxlogin提示SyntaxError Unexpected token <错误

### ISSUE THREAD

**Issue by rm-renmin** [toMatthew/vue-wxlogin#1]
nuxt ssr框架引入vue-wxlogin提示SyntaxError Unexpected token <错误

import wxlogin from 'vue-wxlogin'   这种方式导入时，编译不报错，但是访问引入该组件的页面，提示SyntaxError Unexpected token <错误

**Comment by toMatthew** [comment]
你没有注册组件，components: {wxlogin}
