### ISSUE TITLE
Vue3.0 引用编译错误问题

### ISSUE THREAD

**Issue by zhuqunli** [toMatthew/vue-wxlogin#10]
... node_modules/vue-wxlogin/src/components/vue-wxlogin.vue:57:38
 57: import { createVNode as _createVNode, openBlock as _openBlock, createBlock as _createBlock } from "vue"
                                                                              ^
58: 
59: function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
error during build:
Error: 'openBlock' is not exported by node_modules/vue-wxlogin/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-wxlogin/src/components/vue-wxlogin.vue
....
error Command failed with exit code 1.

开发模式正常使用

**Comment by wen2720** [comment]
请问一下这问题怎么解决？

**Comment by zhuqunli** [comment]
> 请问一下这问题怎么解决？

我弃用他这个库了
