### ISSUE TITLE
Uncaught DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

### ISSUE THREAD

**Issue by xiaoboey** [toMatthew/vue-wxlogin#11]
qrconnect会触发这个异常，导致扫码后微信通知已经登录，但是页面没有回调，还是停留在二维码页面。

在 vue-wxlogin.vue 里的iframe处增加 allow-same-origin可以解决： <iframe sandbox="allow-scripts allow-top-navigation allow-same-origin" ...

**Comment by xiaoboey** [comment]
今天才发现的这个异常，原来都工作正常，可能是微信官方的代码改了

**Comment by shur520** [comment]
感谢楼上的兄弟,这个昨天昨上就登不了了

**Comment by lizhantong** [comment]
我们这原来也工作正常，应该是微信官方的代码改了
