### ISSUE TITLE
请问下组件能否支持self_redirect参数呢？

### ISSUE THREAD

**Issue by choko-oni** [toMatthew/vue-wxlogin#3]
因为跳转回调地址的时候想去掉回调参数code和state，如果直接使用路由跳转，在url上会出现参数一直跟在url上无法去掉的问题，所以想试试组件内iframe内跳转

**Comment by toMatthew** [comment]
不可以，因为code和state是微信官方规定传递的参数，如果不传的话就需要微信那边配合，我这边只是对微信登陆做了个组件化封装而已

**Comment by toMatthew** [comment]
可以的，请更新一下compoment，重新npm，不好意思，比较少登现在才看到，有什么问题保持联系
