### ISSUE TITLE
怎么获取用户授权后返回的code？只能在重定向的链接的参数取吗？

### ISSUE THREAD

**Issue by xiaorongliu** [toMatthew/vue-wxlogin#5]

**Comment by toMatthew** [comment]
https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html

**Comment by toMatthew** [comment]
https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Wechat_Login.html 
微信文档上说的（用户允许授权后，将会重定向到redirect_uri的网址上，并且带上code和state参数）
