### ISSUE TITLE
nuxt 引入组件报错 Unexpected token '<'

### ISSUE THREAD

**Issue by qq31311137** [toMatthew/vue-wxlogin#6]
`
import { defineComponent } from '@nuxtjs/composition-api'
import wxLogin from 'vue-wxlogin'

const wxLoginCSSlink = `${process.env.BASE_URL}/public/stylesheets/wxLogin.css`
export default defineComponent({
  name: 'LoginPopUp',
  components: {
    wxLogin,
  },
})
</script>
`

组件一注册就报错，直接打印也是

**Comment by qq31311137** [comment]
而且为什么这个组件没有导出声明文件，在ts没有办法找到

**Comment by toMatthew** [comment]
刚刚在nuxt的ssr测试了一下没有这样的问题，可以正常使用

**Comment by toMatthew** [comment]
> `
> import { defineComponent } from '@nuxtjs/composition-api'
> import wxLogin from 'vue-wxlogin'
> 
> const wxLoginCSSlink = `${process.env.BASE_URL}/public/stylesheets/wxLogin.css`
> export default defineComponent({
> name: 'LoginPopUp',
> components: {
> wxLogin,
> },
> })
> </script>
> `
> 
> 组件一注册就报错，直接打印也是

步骤
1. 在nuxt.config.js
`
plugins: ['src:'@/plugins/vue-wxlogin']
`
2. 在plugins新建文件vue-wxlogin.js
`import Vue from 'vue';      `
`import wxlogin from 'vue-wxlogin/src/components/vue-wxlogin.vue';     `
`Vue.component('wxlogin', wxlogin);  `
尝试了这样是没问题的

**Comment by toMatthew** [comment]
fixed
