### ISSUE TITLE
nuxt 用不了

### ISSUE THREAD

**Issue by husky-wdy** [toMatthew/vue-wxlogin#8]
同样报 Unexpected token '<' 
试了在两种方案：

一：
nuxt.config.ts中配置
`
plugins: [
   { src: '@/plugins/wxlogin.js', ssr: false }
]
`

二：
直接在页面中引入
`
...
import wxlogin from 'vue-wxlogin';
...
@Component({
  name: 'Login',
  components: { wxlogin }
})
...
`
首先没有ts声明，
vue-wxlogin   会报   Cannot find module 'vue-wxlogin' or its corresponding type declarations

**Comment by toMatthew** [comment]
> 同样报 Unexpected token '<'
> 试了在两种方案：
> 
> 一：
> nuxt.config.ts中配置
> `plugins: [ { src: '@/plugins/wxlogin.js', ssr: false } ]`
> 
> 二：
> 直接在页面中引入
> `... import wxlogin from 'vue-wxlogin'; ... @Component({ name: 'Login', components: { wxlogin } }) ...`
> 首先没有ts声明，
> vue-wxlogin 会报 Cannot find module 'vue-wxlogin' or its corresponding type declarations

步骤
1. 在nuxt.config.js
```
plugins: ['src:'@/plugins/vue-wxlogin']
```
2. 在plugins新建文件vue-wxlogin.js
```import Vue from 'vue';  
import wxlogin from 'vue-wxlogin/src/components/vue-wxlogin.vue';    
Vue.component('wxlogin', wxlogin); 
 ```
尝试了这样是没问题的 in nuxt ver:2.15.3
