### ISSUE TITLE
如果在iframe里面使用的话，怎么才能不在top window里面跳转？

### ISSUE THREAD

**Issue by appbeijing** [toMatthew/vue-wxlogin#9]
如果在iframe里面使用的话，怎么才能不在top window里面跳转

**Comment by appbeijing** [comment]
我的场景是 用户由于长时间登录 导致token过期，现在希望通过一个弹窗扫码再次登录，可是无法跳转，请问这种情况  wxlogin怎么处理？

**Comment by toMatthew** [comment]
在iframe里面使用是没办法避免的

**Comment by toMatthew** [comment]
> 如果在iframe里面使用的话，怎么才能不在top window里面跳转

iframe内使用是没办法避免的这种情况的
